apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "hello world"
  drink: {{ .Values.favorite.drink }}
  dessert: {{ .Values.favorite.dessert | default "cake" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  # you get empty if there is an empty value
  logic-and-null: {{ and .Values.logical.emptyArg .Values.logical.firstArg }}
  # you got latest value of the args
  logic-and-latest: {{ and .Values.favorite.food .Values.favorite.drink }}
  logic-and: {{ and .Values.logical.firstArg .Values.logical.secondArg }}
  logic-and-false: {{ and .Values.logical.firstArg .Values.logical.thirdArg }}
  logic-or-true: {{ or .Values.logical.firstArg .Values.logical.thirdArg }}
  logic-or-false: {{ or .Values.logical.thirdArg .Values.logical.fourthArg }}
  logic-not-false: {{ not .Values.logical.firstArg }}
  logic-not-true: {{ not .Values.logical.thirdArg }}
  logic-eq-number-true: {{ eq .Values.logical.numberOne .Values.logical.numberFour }}
  logic-eq-number-false: {{ eq .Values.logical.numberOne .Values.logical.numberTwo }}
  logic-eq-string-true: {{ eq .Values.logical.stringOne .Values.logical.stringThree }}
  logic-eq-string-false: {{ eq .Values.logical.stringOne .Values.logical.stringTwo }}
  # you cannot compare numbers with string (even when are numbers)
  logic-default-when-is-empty: {{ default "the default value" .Values.logical.emptyDefaultArg }}
  logic-default-when-is-non-empty: {{ default "the default value" .Values.logical.nonEmptyDefaultArg }}
  logic-empty-true: {{ empty .Values.logical.emptyArg }}
  logic-empty-false: {{ empty .Values.logical.nonEmptyArg }}
  # String Functions
  string-print: {{ print "Matt has " .Values.stringFunctions.dog " dogs" }}
  # this prints new line
  string-println: {{ println "Matt has " .Values.stringFunctions.dog " dogs" }}
  string-trim: {{ trim .Values.stringFunctions.trimString }}
  string-trimAll: {{ trimAll "-" .Values.stringFunctions.trimAllSlashes }}
  string-initials: {{ initials .Values.stringFunctions.initialArg }}
  number-random-three-digits: {{ randNumeric 3 }}
  number-random-one-digit: {{ randNumeric 1 }}
  wrap-text: {{ wrap 8 "sometext" }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}

  {{- with .Values.favorite }}
  drink-with: {{ .drink | default "tea" | quote }}
  food-with: {{ .food | upper | quote }}
  {{- end }}

  {{- with .Values.favorite }}
  drink-with-scope: {{ .drink | default "tea" | quote }}
  food-with-scope: {{ .food | upper | quote }}
  release: {{ $.Release.Name }}
  {{- end }}
  toppings: |-
    {{- range .Values.toppings }}
    - {{ . | title | quote}}
    {{- end }}

  # Variable Usage
  {{- $relname := .Release.Name }}
  {{- with .Values.favorite }}
  drink-variable: {{ .drink | quote }}
  food-variable: {{ .food | lower | quote }}
  release: {{ $relname }}
  {{- end}}
  toppings-variable: |-
    {{- range $index, $topping := .Values.toppings }}
    {{ $index }}: {{ $topping }}
    {{- end}}
  # for data structure
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}-structure: {{ $val | quote }}
  {{- end }}

  