apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "hello world"
  drink: {{ .Values.favorite.drink }}
  dessert: {{ .Values.favorite.dessert | default "cake" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  full: {{ and .Values.favorite.food .Values.favorite.drink }}
  logic-and: {{ and .Values.logical.firstArg .Values.logical.secondArg }}
  logic-and-false: {{ and .Values.logical.firstArg .Values.logical.thirdArg }}
  logic-or-true: {{ or .Values.logical.firstArg .Values.logical.thirdArg }}
  logic-or-false: {{ or .Values.logical.thirdArg .Values.logical.fourthArg }}