apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "hello world"
  drink: {{ .Values.favorite.drink }}
  dessert: {{ .Values.favorite.dessert | default "cake" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
